"""Initial migration

Revision ID: 142f79db6dc2
Revises: 
Create Date: 2025-03-18 00:05:17.389407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142f79db6dc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_of_week',
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('groups',
    sa.Column('group_name_ru', sa.String(length=100), nullable=False),
    sa.Column('group_name_en', sa.String(length=100), nullable=False),
    sa.Column('group_description_ru', sa.String(length=255), nullable=True),
    sa.Column('group_description_en', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name_en'),
    sa.UniqueConstraint('group_name_ru')
    )
    op.create_table('lesson_periods',
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_time'),
    sa.UniqueConstraint('lesson_number'),
    sa.UniqueConstraint('start_time')
    )
    op.create_table('lesson_types',
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('roles',
    sa.Column('role_name_ru', sa.String(length=100), nullable=False),
    sa.Column('role_name_en', sa.String(length=100), nullable=False),
    sa.Column('role_description_ru', sa.String(length=255), nullable=True),
    sa.Column('role_description_en', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name_en'),
    sa.UniqueConstraint('role_name_ru')
    )
    op.create_table('sites',
    sa.Column('site_name_ru', sa.CHAR(length=50), nullable=False),
    sa.Column('site_name_en', sa.CHAR(length=50), nullable=False),
    sa.Column('site_description_ru', sa.String(length=255), nullable=True),
    sa.Column('site_description_en', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name_en'),
    sa.UniqueConstraint('site_name_ru')
    )
    op.create_table('subjects',
    sa.Column('subject_name_ru', sa.String(length=255), nullable=False),
    sa.Column('subject_name_en', sa.String(length=255), nullable=False),
    sa.Column('subject_description_ru', sa.String(length=255), nullable=True),
    sa.Column('subject_description_en', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_name_en'),
    sa.UniqueConstraint('subject_name_ru')
    )
    op.create_table('terms',
    sa.Column('term_name_ru', sa.String(length=100), nullable=False),
    sa.Column('term_name_en', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_name_en'),
    sa.UniqueConstraint('term_name_ru')
    )
    op.create_table('week_types',
    sa.Column('day_number', sa.Integer(), nullable=False, comment='Numeric representation of day of week (e.g., 1=Monday, 2=Tuesday, ...)'),
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_number'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('users',
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('administrators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name_ru', sa.String(length=255), nullable=False),
    sa.Column('first_name_en', sa.String(length=255), nullable=False),
    sa.Column('last_name_ru', sa.String(length=255), nullable=False),
    sa.Column('last_name_en', sa.String(length=255), nullable=False),
    sa.Column('patronymic_ru', sa.String(length=255), nullable=False),
    sa.Column('patronymic_en', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('students',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name_ru', sa.String(length=255), nullable=False),
    sa.Column('first_name_en', sa.String(length=255), nullable=False),
    sa.Column('last_name_ru', sa.String(length=255), nullable=False),
    sa.Column('last_name_en', sa.String(length=255), nullable=False),
    sa.Column('patronymic_ru', sa.String(length=255), nullable=False),
    sa.Column('patronymic_en', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teachers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name_ru', sa.String(length=255), nullable=False),
    sa.Column('first_name_en', sa.String(length=255), nullable=False),
    sa.Column('last_name_ru', sa.String(length=255), nullable=False),
    sa.Column('last_name_en', sa.String(length=255), nullable=False),
    sa.Column('patronymic_ru', sa.String(length=255), nullable=False),
    sa.Column('patronymic_en', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('term_schedule',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('week_type_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week_id', sa.Integer(), nullable=False),
    sa.Column('lesson_period_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('lesson_type_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=False, comment='True if the lesson is conducted online'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_of_week_id'], ['day_of_week.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_period_id'], ['lesson_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_type_id'], ['lesson_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_type_id'], ['week_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['term_schedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_groups',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['term_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_groups')
    op.drop_table('attendance')
    op.drop_table('term_schedule')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('administrators')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('week_types')
    op.drop_table('terms')
    op.drop_table('subjects')
    op.drop_table('sites')
    op.drop_table('roles')
    op.drop_table('lesson_types')
    op.drop_table('lesson_periods')
    op.drop_table('groups')
    op.drop_table('day_of_week')
    # ### end Alembic commands ###
