"""fix: make relationship not optional in TermSchedule

Revision ID: 448a1a1e9322
Revises: 9871227ab074
Create Date: 2025-03-20 01:55:14.487689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448a1a1e9322'
down_revision: Union[str, None] = '9871227ab074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
