"""fix: use String instead of char in Site table

Revision ID: 9871227ab074
Revises: ac2867e91513
Create Date: 2025-03-20 01:30:02.271584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9871227ab074'
down_revision: Union[str, None] = 'ac2867e91513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'site_name_ru',
               existing_type=sa.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('sites', 'site_name_en',
               existing_type=sa.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'site_name_en',
               existing_type=sa.String(length=50),
               type_=sa.CHAR(length=50),
               existing_nullable=False)
    op.alter_column('sites', 'site_name_ru',
               existing_type=sa.String(length=50),
               type_=sa.CHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
